// db/postgres-compat.js
// Pre-migration compatibility helpers + dialect translator stub.
// Use translateSqlForPg(sql) on each statement during migration to flag
// or auto-rewrite known SQLite-only patterns.
'use strict';

const SQLITE_ONLY_PATTERNS = [
  { name: 'AUTOINCREMENT',         re: /\bAUTOINCREMENT\b/gi,                  pgEquivalent: 'GENERATED BY DEFAULT AS IDENTITY' },
  { name: 'INTEGER PRIMARY KEY',   re: /INTEGER\s+PRIMARY\s+KEY/gi,            pgEquivalent: 'BIGSERIAL PRIMARY KEY' },
  { name: 'datetime("now")',       re: /datetime\(\s*['"]now['"]\s*\)/gi,      pgEquivalent: 'NOW()' },
  { name: 'CURRENT_TIMESTAMP text',re: /\bCURRENT_TIMESTAMP\b/g,               pgEquivalent: 'NOW()' },
  { name: 'julianday()',           re: /julianday\s*\(/gi,                     pgEquivalent: 'EXTRACT(EPOCH FROM ...)/86400' },
  { name: 'GROUP_CONCAT',          re: /GROUP_CONCAT\s*\(/gi,                  pgEquivalent: 'STRING_AGG(... , \',\')' },
  { name: 'GLOB',                  re: /\bGLOB\b/gi,                           pgEquivalent: 'SIMILAR TO / regex (~)' },
  { name: 'INSERT OR REPLACE',     re: /\bINSERT\s+OR\s+REPLACE\b/gi,          pgEquivalent: 'INSERT ... ON CONFLICT DO UPDATE' },
  { name: 'INSERT OR IGNORE',      re: /\bINSERT\s+OR\s+IGNORE\b/gi,           pgEquivalent: 'INSERT ... ON CONFLICT DO NOTHING' },
  { name: 'PRAGMA',                re: /\bPRAGMA\b/gi,                         pgEquivalent: 'information_schema queries' },
  { name: 'LIKE (case-insensitive)',re:/\bLIKE\b/gi,                           pgEquivalent: 'ILIKE (PG LIKE is case-sensitive)' },
  { name: 'sqlite_master',         re: /\bsqlite_master\b/gi,                  pgEquivalent: 'pg_catalog / information_schema' },
];

function flagSqlForPg(sql) {
  if (typeof sql !== 'string') return [];
  const flags = [];
  for (const p of SQLITE_ONLY_PATTERNS) {
    if (p.re.test(sql)) flags.push({ pattern: p.name, suggested: p.pgEquivalent });
    p.re.lastIndex = 0;
  }
  return flags;
}

// Best-effort auto-rewrite for the safe subset (datetime/now, AUTOINCREMENT,
// INSERT OR REPLACE, GROUP_CONCAT). Use during a controlled migration only.
function translateSqlForPg(sql) {
  if (typeof sql !== 'string') return sql;
  let out = sql;
  out = out.replace(/AUTOINCREMENT/gi, '');
  out = out.replace(/INTEGER\s+PRIMARY\s+KEY/gi, 'BIGSERIAL PRIMARY KEY');
  out = out.replace(/datetime\(\s*['"]now['"]\s*\)/gi, 'NOW()');
  out = out.replace(/\bGROUP_CONCAT\s*\(\s*([^)]+?)\s*\)/gi, "STRING_AGG($1::text, ',')");
  out = out.replace(/\bINSERT\s+OR\s+REPLACE\s+INTO\b/gi, 'INSERT INTO');
  out = out.replace(/\bINSERT\s+OR\s+IGNORE\s+INTO\b/gi, 'INSERT INTO');
  // NOTE: ON CONFLICT clauses must be added per-table by hand; flagged not auto-rewritten.
  return out;
}

// Scan a directory of route/.js files for incompatible SQL strings.
function scanProjectForPgIssues(rootDir) {
  const fs = require('fs');
  const path = require('path');
  const results = [];
  function walk(dir) {
    let entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch (e) { return; }
    for (const ent of entries) {
      if (ent.name === 'node_modules' || ent.name.startsWith('.')) continue;
      const fp = path.join(dir, ent.name);
      if (ent.isDirectory()) walk(fp);
      else if (ent.isFile() && ent.name.endsWith('.js')) {
        let txt; try { txt = fs.readFileSync(fp, 'utf8'); } catch (e) { continue; }
        const flags = flagSqlForPg(txt);
        if (flags.length) results.push({ file: fp, flags });
      }
    }
  }
  walk(rootDir);
  return results;
}

module.exports = { flagSqlForPg, translateSqlForPg, scanProjectForPgIssues, SQLITE_ONLY_PATTERNS };
